# -*- coding: utf-8 -*-
"""DS-capstone.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Azbsg7RilMzR8WRlvo87dwvFbughXLCT
"""

from matplotlib import pyplot as plt
import numpy as np
import seaborn as sns
import pandas as pd
sns.set()

list0=[2, 5, 7, 8, 10, 14, 17, 19, 21, 23, 25, 26, 31, 32, 34, 42]
list1=[0, 3, 4, 5, 6, 8, 9, 12, 13, 16, 18, 19, 20, 21, 23, 24]
list2=[3, 4, 5, 8, 10, 13, 15, 16, 19, 20, 22, 23, 24, 26, 29, 31]
list3=[0, 1, 2, 4, 6, 10, 12, 14, 17, 19, 20, 22, 23, 24, 25, 27]
list4=[0, 2, 4, 5, 8, 10, 13, 15, 17, 19, 21, 24, 26, 29, 32, 35]

list00=[19, 17, 49, 15, 35, 5, 42, 32, 26, 13, 21, 16, 9, 25, 41, 4]
list10=[19, 43, 22, 4, 45, 21, 20, 49, 13, 42, 15, 12, 5, 16, 0, 38]
list20=[11, 34, 43, 36, 48, 2, 47, 26, 44, 37, 14, 6, 28, 27, 1, 42]
list30=[34, 47, 48, 43, 11, 2, 44, 27, 32, 17, 37, 36, 7, 41, 1, 6]
list40=[3, 13, 19, 41, 42, 15, 5, 4, 21, 36, 26, 17, 49, 38, 37, 44]

list5=list0+list1+list2+list3+list4
list50=list00+list10+list20+list30+list40
ground_truth=[10,140,500,46,98,5,500,186,11,9,500,500,500,500,12,5,45,338,4,2,0,3,71,21,192,116,52,42,1,61,45,139,1,4,2,167,53,2,6,10,4,7,22,82,23,21,16,9,13,5]

plt.hist(list5,bins=50,alpha=0.5,label='Multi-objective')
plt.hist(list50,bins=50,alpha=0.5,label='Common')
plt.scatter(range(50),np.array(ground_truth)/100,c='green',s=5,label='Scaled popularity ground truth')
plt.title('Comparison between common and multi-objective method')
plt.xlabel('Book Index')
plt.ylabel('Recommendation times')
plt.legend()
plt.show()

ground_truth=[10,140,500,46,98,5,500,186,11,9,500,500,500,500,12,5,45,338,4,2,1,3,71,21,192,116,52,42,1,61,45,139,1,4,2,167,53,2,6,10,4,7,22,82,23,21,16,9,13,5]
j=[3., 1., 3., 2., 4., 4., 0., 2., 1., 4., 1., 4., 0., 0., 2., 3., 2.,
        2., 0., 2., 3., 1., 5., 3., 0., 3., 2., 4., 4., 2., 3., 0., 1., 0.,
        2., 0., 2., 0., 2., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 1.]
k=[1., 2., 2., 1., 3., 3., 2., 1., 0., 1., 0., 2., 1., 3., 1., 3., 2.,
        3., 0., 3., 1., 3., 1., 0., 0., 1., 3., 2., 1., 0., 0., 0., 2., 0.,
        2., 1., 3., 3., 2., 0., 0., 3., 4., 3., 3., 1., 0., 2., 2., 3.]
result0=np.array(j)/np.array(ground_truth)
result1=np.array(k)/np.array(ground_truth)
plt.scatter(range(50),result0,alpha=0.6,label='Multi-objective')
plt.scatter(range(50),result1,alpha=0.6,label='Common')
plt.title('Comparison between common and multi-objective method')
plt.xlabel('Book Index')
plt.ylabel('No.rec / popularity')
plt.legend()
plt.show()

ground_truth=[10,140,500,46,98,5,500,186,11,9,500,500,500,500,12,5,45,338,4,2,1,3,71,21,192,116,52,42,1,61,45,139,1,4,2,167,53,2,6,10,4,7,22,82,23,21,16,9,13,5]
j=[3., 1., 3., 2., 4., 4., 0., 2., 1., 4., 1., 4., 0., 0., 2., 3., 2.,
        2., 0., 2., 3., 1., 5., 3., 0., 3., 2., 4., 4., 2., 3., 0., 1., 0.,
        2., 0., 2., 0., 2., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 1.]
k=[1., 2., 2., 1., 3., 3., 2., 1., 0., 1., 0., 2., 1., 3., 1., 3., 2.,
        3., 0., 3., 1., 3., 1., 0., 0., 1., 3., 2., 1., 0., 0., 0., 2., 0.,
        2., 1., 3., 3., 2., 0., 0., 3., 4., 3., 3., 1., 0., 2., 2., 3.]
result0=np.array(j)*100+np.array(ground_truth)
print(np.std(result0[0:30]))
result1=np.array(k)*100+np.array(ground_truth)
print(np.std(result1[0:30]))
plt.scatter(range(30),result1[0:30],alpha=0.65,label='Single-objective',marker='v')
plt.scatter(range(30),result0[0:30],alpha=0.65,label='Multi-objective',marker='^')

plt.title('Comparison between single-objective and multi-objective method')
plt.xlabel('Book Index')
plt.ylabel('Long term borrowing frequency')
plt.legend()
plt.show()

group1=result0[0:30]
group2=result1[0:30]
d = {'Single-objective': group1, 'Multi-objective': group2}
df = pd.DataFrame(data=d)
sns.displot(df,label='Long-time frequency',alpha=0.3,rug=True, bins=10,kde=True)